# espanso基本設定ファイル
# https://espanso.org/docs/configuration/

# 基本設定
auto_restart: true
preserve_clipboard: true
paste_shortcut: "CTRL+V"

# キーボード設定
toggle_key: "ALT+SPACE"
search_trigger: "ESC"
search_shortcut: "ALT+SPACE"

# マッチング設定
enable_active: true
backspace_limit: 3

# ログ設定
log_level: "INFO"

# セキュリティ設定
secure_input_notification: true

# クリップボード設定
clipboard_threshold: 100
restore_clipboard_delay: 300

# パフォーマンス設定
inject_delay: 0
key_delay: 0
word_separators: [" ", ",", ".", "?", "!", ";", ":"]

# 除外アプリケーション
filter_title: ".*Terminal.*|.*iTerm.*"
filter_class: "terminal"

# 日本語対応
undo_backspace: true

